import org.gradle.process.CommandLineArgumentProvider
import org.jetbrains.changelog.Changelog
import org.jetbrains.intellij.platform.gradle.Constants.Tasks
import org.jetbrains.intellij.platform.gradle.TestFrameworkType
import kotlin.io.path.exists

plugins {
    id("org.jetbrains.kotlin.jvm")
    id("org.jetbrains.changelog")
    id("org.jetbrains.intellij.platform")
}

val dotnetSolution = providers.gradleProperty("dotnetSolution").get()
val dotnetBuildConfiguration = providers.gradleProperty("dotnetBuildConfiguration").get()
val dotnetSrcDir = layout.projectDirectory.dir("src/dotnet")

// Sandbox plugin directory name == the plugin's display name.
val pluginDirName = "Component Investigation"

// Source set that picks up the Kotlin protocol code generated by rdgen (see :protocol).
sourceSets {
    main {
        kotlin.srcDir(layout.buildDirectory.dir("generated/model"))
    }
}

dependencies {
    testImplementation(libs.junit)

    intellijPlatform {
        // useInstaller = false resolves the non-installer (snapshot) Rider layout, which — unlike
        // the default installer layout — ships lib/rd/rider-model.jar that :protocol/rdgen needs.
        rider(providers.gradleProperty("platformVersion")) {
            useInstaller = false
        }
        // Needed to compile against MarkdownLinkOpener (our overriding service). Optional at runtime.
        bundledPlugin("org.intellij.plugins.markdown")
        testFramework(TestFrameworkType.Platform)
    }
}

intellijPlatform {
    pluginConfiguration {
        name = pluginDirName
        version = providers.gradleProperty("version")

        ideaVersion {
            // The ReSharper backend SDK is pinned to 2026.1, so the plugin targets only 2026.1.x.
            sinceBuild = "261"
            untilBuild = "261.*"
        }

        vendor {
            name = providers.gradleProperty("vendorName")
            email = providers.gradleProperty("vendorEmail")
            url = providers.gradleProperty("vendorUrl")
        }

        // Release notes pulled from CHANGELOG.md (org.jetbrains.changelog).
        changeNotes = providers.gradleProperty("version").map { pluginVersion ->
            with(changelog) {
                renderItem(
                    (getOrNull(pluginVersion) ?: getUnreleased())
                        .withHeader(false)
                        .withEmptySections(false),
                    Changelog.OutputType.HTML,
                )
            }
        }
    }

    // Marketplace requires signed plugins. Provide the cert/key via environment variables:
    //   CERTIFICATE_CHAIN, PRIVATE_KEY, PRIVATE_KEY_PASSWORD  (see signPlugin task docs).
    signing {
        certificateChain = providers.environmentVariable("CERTIFICATE_CHAIN")
        privateKey = providers.environmentVariable("PRIVATE_KEY")
        password = providers.environmentVariable("PRIVATE_KEY_PASSWORD")
    }

    // publishPlugin reads the Marketplace token from PUBLISH_TOKEN. A `-suffix` version (e.g.
    // 1.0.0-beta) publishes to that channel; a plain version publishes to the stable channel.
    publishing {
        token = providers.environmentVariable("PUBLISH_TOKEN")
        channels = providers.gradleProperty("version").map {
            listOf(it.substringAfter('-', "").ifEmpty { "default" })
        }
    }

    // `verifyPlugin` checks binary compatibility against the target IDE(s).
    pluginVerification {
        ides {
            recommended()
        }
    }
}

// Pin Java + Kotlin to the same, supported JVM (21). Foojay auto-provisions the JDK regardless
// of which java/JBR launches Gradle (the 2025.3 platform targets JDK 21).
kotlin {
    jvmToolchain(21)
}

// --- Expose the Rider model jar so :protocol can run rdgen against it. -------------------
// Workaround for https://github.com/JetBrains/intellij-platform-gradle-plugin/issues/1903
val riderModel: Configuration by configurations.creating {
    isCanBeConsumed = true
    isCanBeResolved = false
}

artifacts {
    add(riderModel.name, provider {
        intellijPlatform.platformPath.resolve("lib/rd/rider-model.jar").also {
            check(it.exists()) { "rider-model.jar not found at $it" }
        }
    }) {
        builtBy(Tasks.INITIALIZE_INTELLIJ_PLATFORM_PLUGIN)
    }
}

// --- .NET backend build -----------------------------------------------------------------
val compileDotNet by tasks.registering(Exec::class) {
    group = "backend"
    description = "Builds the ReSharper backend solution."
    // rdgen must run first so the generated C# model exists.
    dependsOn(":protocol:rdgen")
    workingDir = dotnetSrcDir.asFile
    commandLine("dotnet", "build", dotnetSolution, "-c", dotnetBuildConfiguration)
}

tasks {
    // Frontend Kotlin needs the generated model -> ensure rdgen ran.
    compileKotlin {
        dependsOn(":protocol:rdgen")
    }

    // Open this solution automatically when launching the sandbox Rider via runIde.
    runIde {
        argumentProviders.add(CommandLineArgumentProvider {
            listOf("/home/user/doc/del/eShopOnWeb/eShopOnWeb.sln")
        })
    }

    // Bundle the compiled backend DLLs into the plugin's dotnet/ folder so Rider loads the
    // ReSharper extension. Layout: <plugin>/dotnet/*.dll
    prepareSandbox {
        dependsOn(compileDotNet)
        // NB: the sandbox plugin directory is named after the gradle project (rootProject.name),
        // NOT the plugin display name. The backend DLLs must land in THAT dir's dotnet/ folder,
        // otherwise Rider's ReSharper host never loads them.
        from(dotnetSrcDir.dir("ComponentInvestigation.Rider/bin/$dotnetBuildConfiguration")) {
            include("ComponentInvestigation.Rider.dll")
            include("ComponentInvestigation.Rider.pdb")
            into("${rootProject.name}/dotnet")
        }
    }
}
